**STRUCTURED AND UNSTUCTURED DATA**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Structured data is data that has a standardized format for efficient access by software and humans alike.


Structured data have a structure, rows and columns .


Structured data is oraganized , eg: csv file,Names, addresses, credit card numbers, telephone numbers etc.

Unstructured data is information that doesn't have a predetermined structure or format.

Information that is not arranged.

Unstructured data is unorganized .

No specific structure , eg: image files,Emails,PDFs etc

**3 TYPES OF IMAGES**


1.Coloured


2.Grey Scale


3.Black and White

**LAYERS OF IMAGES**

3 layers--coloured images - R G B

2 layers--black and white - B W

1 layers--grey scale-intensity layer -pixel range { 0to 255}

In [2]:
import pandas as pd
from sklearn import svm
import os
from skimage.transform import resize    #to resize the image
from skimage.io import imread
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
os.listdir('/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data')

['cats', 'dogs']

In [4]:
len(os.listdir('/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data'))

2

In [5]:
len(os.listdir('/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data/cats'))

70

In [6]:
len(os.listdir('/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data/dogs'))

70

In [7]:
len(os.path.join('/content/drive/MyDrive/DATA SCIENCE/Machine Learning/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data','dogs'))

115

In [8]:
dogpath = os.path.join('/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data/dogs')

sum = 0
for img in os.listdir(dogpath):
  sum = sum + 1
print(sum)

70


In [9]:
flat_data_arr = []
target_arr = []
categories = ['cats','dogs']

datadir = '/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/Data'

In [10]:
for i in categories:

  print('loading...category:',i)

  path = os.path.join(datadir,i)

  for img in os.listdir(path):

    img_array = imread(os.path.join(path,img))

    img_resized = resize(img_array, (150, 150,3))

    flat_data_arr.append(img_resized.flatten())

    target_arr.append(categories.index(i))

    print('loaded category:',i)



loading...category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded category: cats
loaded 

In [11]:
len(flat_data_arr)

140

In [12]:
flat_data = np.array(flat_data_arr)
target = np.array(target_arr)
df = pd.DataFrame(flat_data)

In [13]:
df.head()

0         1         2         3         4         5         6      \
0  0.711820  0.706830  0.698630  0.738233  0.725065  0.714140  0.758801   
1  0.777090  0.737870  0.600616  0.811394  0.770670  0.633918  0.753518   
2  0.460489  0.413430  0.366371  0.455881  0.408822  0.361763  0.466294   
3  0.286301  0.247085  0.243164  0.296888  0.257672  0.253751  0.358370   
4  0.066459  0.050772  0.046851  0.066493  0.050807  0.046885  0.066656   

      7         8         9      ...     67490     67491     67492     67493  \
0  0.743134  0.731376  0.775598  ...  0.614892  0.715918  0.657519  0.603041   
1  0.704044  0.570207  0.746241  ...  0.324756  0.529818  0.461101  0.384491   
2  0.419235  0.372176  0.484487  ...  0.749881  0.784373  0.772608  0.753000   
3  0.319154  0.315232  0.364896  ...  0.660789  0.786018  0.731116  0.680135   
4  0.050969  0.047048  0.066667  ...  0.047049  0.106625  0.044847  0.042909   

      67494     67495     67496     67497     67498     67499  
0  0.704903  0.643448  0.585915  0.686139  0.625675  0.569133  
1  0.740867  0.684632  0.575485  0.749805  0.694901  0.581188  
2  0.787661  0.775896  0.756289  0.788307  0.776543  0.756935  
3  0.739877  0.684975  0.633994  0.770878  0.715976  0.664995  
4  0.138086  0.038445  0.038020  0.187227  0.059644  0.061446  

[5 rows x 67500 columns]

In [14]:
df.shape

(140, 67500)

In [15]:
df['target'] = target

In [16]:
df

0         1         2         3         4         5         6  \
0    0.711820  0.706830  0.698630  0.738233  0.725065  0.714140  0.758801   
1    0.777090  0.737870  0.600616  0.811394  0.770670  0.633918  0.753518   
2    0.460489  0.413430  0.366371  0.455881  0.408822  0.361763  0.466294   
3    0.286301  0.247085  0.243164  0.296888  0.257672  0.253751  0.358370   
4    0.066459  0.050772  0.046851  0.066493  0.050807  0.046885  0.066656   
..        ...       ...       ...       ...       ...       ...       ...   
135  0.407531  0.589320  0.184941  0.367488  0.559873  0.183857  0.349511   
136  0.955698  0.764370  0.473220  0.962568  0.741927  0.449380  0.951398   
137  0.903570  0.668276  0.523178  0.897105  0.662395  0.515411  0.888246   
138  0.353188  0.364953  0.290443  0.352146  0.363911  0.289399  0.357820   
139  0.495181  0.356688  0.225479  0.505563  0.362332  0.232841  0.520498   

            7         8         9  ...     67491     67492     67493  \
0    0.743134  0.731376  0.775598  ...  0.715918  0.657519  0.603041   
1    0.704044  0.570207  0.746241  ...  0.529818  0.461101  0.384491   
2    0.419235  0.372176  0.484487  ...  0.784373  0.772608  0.753000   
3    0.319154  0.315232  0.364896  ...  0.786018  0.731116  0.680135   
4    0.050969  0.047048  0.066667  ...  0.106625  0.044847  0.042909   
..        ...       ...       ...  ...       ...       ...       ...   
135  0.541786  0.190613  0.347483  ...  0.298775  0.492980  0.180028   
136  0.744545  0.446765  0.954816  ...  0.504223  0.265205  0.097724   
137  0.646552  0.492041  0.881283  ...  0.138033  0.259602  0.098817   
138  0.369149  0.293553  0.357423  ...  0.993155  0.975239  0.960783   
139  0.363470  0.239215  0.523316  ...  0.503778  0.287529  0.166141   

        67494     67495     67496     67497     67498     67499  target  
0    0.704903  0.643448  0.585915  0.686139  0.625675  0.569133       0  
1    0.740867  0.684632  0.575485  0.749805  0.694901  0.581188       0  
2    0.787661  0.775896  0.756289  0.788307  0.776543  0.756935       0  
3    0.739877  0.684975  0.633994  0.770878  0.715976  0.664995       0  
4    0.138086  0.038445  0.038020  0.187227  0.059644  0.061446       0  
..        ...       ...       ...       ...       ...       ...     ...  
135  0.370588  0.546685  0.187446  0.382166  0.528625  0.188819       1  
136  0.488168  0.260536  0.092562  0.592050  0.363520  0.169403       1  
137  0.104807  0.226375  0.065591  0.129354  0.250923  0.090138       1  
138  0.995273  0.967552  0.944873  0.995474  0.958940  0.928509       1  
139  0.499107  0.283420  0.161852  0.493736  0.278050  0.156481       1  

[140 rows x 67501 columns]

In [17]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.20, random_state = 0)

In [19]:

clf = svm.SVC()

clf.fit(x_train,y_train)

SVC()

In [20]:
y_pred = clf.predict(x_test)

In [21]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1])

In [22]:
y_test

45     0
59     0
7      0
50     0
92     1
27     0
131    1
137    1
122    1
8      0
111    1
16     0
63     0
76     1
123    1
97     1
104    1
110    1
33     0
91     1
90     1
22     0
102    1
24     0
2      0
51     0
26     0
71     1
Name: target, dtype: int64

In [23]:
from sklearn.metrics import accuracy_score
sva = accuracy_score(y_test,y_pred)
print('Accuracy Score = ',accuracy_score(y_test,y_pred))

Accuracy Score =  0.5714285714285714


**MATRIX DEFINITIONS**

**F1 Score**

The F1 is the weighted harmonic mean of precision and recall.

The closer the value of the F1 score is to 1.0, the better the expected performance of the model is **Support ; Support** is the number of actual occurences of the class in the dataset.It doesnt vary between models,it just diagnoses the performance evaluation process.



In [25]:
img.shape

(67500,)

In [26]:
path = '/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/cat_525.jpg'

img = imread(path)
img = resize(img,(150,150,3)).flatten().reshape(1,-1)
clf.predict(img)

array([0])

In [27]:
path = '/content/drive/MyDrive/DATA SCIENCE/MACHINE LEARNING/MACHINE LEARNING ALGORITHMS/SVM/IMAGE CLASSIFICATION/dog_534.jpg'

img = imread(path)
img = resize(img,(150,150,3)).flatten().reshape(1,-1)
clf.predict(img)

array([1])

**OVER FITTING**

When a model performs very well for training data but has poor performance with test data (new data), it is known as overfiting in this case, the machine leaming model leams the details and noise in the training data such that it negatively affects the performance of the model on test data.



Overfitting can happen due to low bias and high variance. Reasons for Overfitting Data used for training is not cleaned and contains noise (garbage values) in it The model has a high warlance.

The size of the training dataset used is not enough.

The model is too complex.

**UNDER FITTING**

When a model has not learned the patterns in the training data well and is unable to generalize well on the new data, it is known as underfitting An undefit model has poor performance on the training data and will result in unrellable predictions. Underfitting occurs due to high bies and low variance.



Reesons for Underfining Dats used for training is not cleaned and contains noise (garbage values) in its The model has a high bias.

The sum of the training datasit used is not enough.

The model is too single.



**Inappropriate Features:**If important features are not included in the model or relevant features are included, the model may struggle to capture the true relationship in the data, leading to underfieting.

**GOOD FIT IN MACHINE LEARNING**

To find the good fit model, you need to look at the performance of a machine warning model over time with the truthing data. As the algorten leums over tone, the error for the model on the training data radices, as well as the amar on the tast datanet. If you train the model for too long, the model may learn the unnecessary details and the stue in the training at and hence lead to overfitting. Inorder to achieve a good fit you need to stop training at a point where the error starts to increase.

**Bias :**

Bias in a prediction error that is Introduced in the model due to oversimplifying the machine learning algoritms. Or is the difference between the predicted values and the actual values.



**Variance :**

If the machine learning model performs well with the training dataset,but does not perform well with the test dataset then variance.

In [ ]:
# right fit = low bias and low variance

# overfit = low bias and high variance

# underfit = high bias and low variance

# badfit = high bias and high variance --- void condition

over fit - training high and testing low

underfit - training low and testing low

best fit - training high and testing high

bad fit - training low and testing high --- void condition